//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cthoadon
    {
        public int maHoaDon { get; set; }
        public int maSach { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual tb_hoadon tb_hoadon { get; set; }
        public virtual tb_sach tb_sach { get; set; }
    }
}
