//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_hoadon()
        {
            this.tb_cthoadon = new HashSet<tb_cthoadon>();
        }
    
        public int maHoaDon { get; set; }
        public Nullable<int> maKhachHang { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<int> manv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cthoadon> tb_cthoadon { get; set; }
        public virtual tb_khachhang tb_khachhang { get; set; }
        public virtual tb_nhanvien tb_nhanvien { get; set; }
    }
}
