//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_nhacungcap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_nhacungcap()
        {
            this.tb_phieunhap = new HashSet<tb_phieunhap>();
        }
    
        public int maNhaCungCap { get; set; }
        public string tenNhaCungCap { get; set; }
        public string diaChi { get; set; }
        public string sdtNhaCungCap { get; set; }
        public string ghichu { get; set; }
        public Nullable<double> chietkhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_phieunhap> tb_phieunhap { get; set; }
    }
}
