//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_phieunhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_phieunhap()
        {
            this.tb_ctphieunhap = new HashSet<tb_ctphieunhap>();
        }
    
        public int maPhieuNhap { get; set; }
        public Nullable<int> maNhanVien { get; set; }
        public Nullable<int> maNhaCungCap { get; set; }
        public Nullable<System.DateTime> ngayNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ctphieunhap> tb_ctphieunhap { get; set; }
        public virtual tb_nhacungcap tb_nhacungcap { get; set; }
        public virtual tb_nhanvien tb_nhanvien { get; set; }
    }
}
